[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[context.production]
  environment = { NODE_VERSION = "14.16.0" }
  
[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"