/** @typedef {{ padding: number, styles: string[] }} Shape */
/** @typedef { 'boat' | 'butterfly' | 'camel' | 'cat' | 'fish' | 'heart' | 'horse' | 'house' | 'mouse' | 'rabbit' | 'rocket' | 'scorpion' | 'serpent' | 'swan' } Key */
/** @type Object.<Key, Shape> */
export default {
  boat: {
    padding: 1.5,
    styles: [
      "transform: translate(5.5px, 3px) rotate(180deg)",
      "transform: translate(1.5px, -1px) rotate(0deg)",
      "transform: translate(1.5px, 1.586px) rotate(-135deg)",
      "transform: translate(0.086px, 1.586px) rotate(135deg)",
      "transform: translate(1.5px, 3px) rotate(45deg)",
      "transform: translate(1.5px, 1.586px) rotate(135deg)",
      "transform: translate(0.086px, 3px) rotate(45deg)",
    ],
  },
  butterfly: {
    padding: 1,
    styles: [
      "transform: translate(2px, 2px) rotate(-45deg)",
      "transform: translate(2px, 2px) rotate(135deg)",
      "transform: translate(3.414px, 2px) rotate(45deg)",
      "transform: translate(2px, 3.414px) rotate(45deg)",
      "transform: translate(-0.828px, 2px) rotate(45deg)",
      "transform: translate(2px, 2px) rotate(45deg)",
      "transform: translate(2px, 2px) rotate(135deg)",
    ],
  },
  camel: {
    padding: 1.5,
    styles: [
      "transform: translate(0.5px, 5px) rotate(-90deg)",
      "transform: translate(1.5px, 2px) rotate(-45deg)",
      "transform: translate(-0.5px, 0px) rotate(0deg)",
      "transform: translate(0.5px, -1px) rotate(180deg)",
      "transform: translate(4.328px, 2px) rotate(-135deg)",
      "transform: translate(0.5px, 1px) rotate(0deg)",
      "transform: translate(-0.5px, 0px) rotate(90deg)",
    ],
  },
  cat: {
    padding: 2.5,
    styles: [
      "transform: translate(1px, 2.672px) rotate(45deg)",
      "transform: translate(3px, 4.672px) rotate(180deg)",
      "transform: translate(3px, -1.329px) rotate(0deg)",
      "transform: translate(2px, -2.328px) rotate(90deg)",
      "transform: translate(3px, 3.5px) rotate(-45deg)",
      "transform: translate(2px, -0.329px) rotate(0deg)",
      "transform: translate(1px, 5.5px) rotate(-135deg)",
    ],
  },
  fish: {
    padding: 1.5,
    styles: [
      "transform: translate(2.5px, -0.5px) rotate(45deg)",
      "transform: translate(2.5px, 5.156px) rotate(-135deg)",
      "transform: translate(2.5px, 1.621px) rotate(-135deg)",
      "transform: translate(1.086px, 3.035px) rotate(45deg)",
      "transform: translate(-0.328px, 3.035px) rotate(-45deg)",
      "transform: translate(1.086px, 1.621px) rotate(45deg)",
      "transform: translate(1.086px, 1.621px) rotate(135deg)",
    ],
  },
  goat: {
    padding: 2,
    styles: [
      "transform: translate(2.086px, 1.414px) rotate(135deg)",
      "transform: translate(0.5px, 3px) rotate(-90deg)",
      "transform: translate(4.5px, 3px) rotate(135deg)",
      "transform: translate(-0.742px, 2.414px) rotate(-90deg)",
      "transform: translate(5.5px, 2px) rotate(-90deg)",
      "transform: translate(2.5px, 1px) rotate(0deg)",
      "transform: translate(2.672px, -1.414px) rotate(45deg)",
    ],
  },
  heart: {
    padding: 1,
    styles: [
      "transform: translate(1px, 1.5px) rotate(0deg)",
      "transform: translate(1px, 1.5px) rotate(-90deg)",
      "transform: translate(1px, -0.5px) rotate(90deg)",
      "transform: translate(1px, 1.5px) rotate(90deg)",
      "transform: translate(1px, 3.5px) rotate(-90deg)",
      "transform: translate(1px, 3.5px) rotate(0deg)",
      "transform: translate(-1px, 1.5px) rotate(0deg)",
    ],
  },
  horse: {
    padding: 2,
    styles: [
      "transform: translate(2.5px, 5px) rotate(-90deg)",
      "transform: translate(-0.328px, 1px) rotate(-45deg)",
      "transform: translate(2.5px, 5.5px) rotate(-135deg)",
      "transform: translate(-1.328px, 2px) rotate(0deg)",
      "transform: translate(2.5px, -0.414px) rotate(-135deg)",
      "transform: translate(2.5px, 1px) rotate(-135deg)",
      "transform: translate(4.5px, 3px) rotate(90deg)",
    ],
  },
  house: {
    padding: 1,
    styles: [
      "transform: translate(3.414px, 2.414px) rotate(180deg)",
      "transform: translate(0px, 4.414px) rotate(-90deg)",
      "transform: translate(3px, 3.414px) rotate(-90deg)",
      "transform: translate(4px, 4.414px) rotate(-90deg)",
      "transform: translate(2px, 2.414px) rotate(180deg)",
      "transform: translate(2px, -0.414px) rotate(45deg)",
      "transform: translate(2px, 1px) rotate(45deg)",
    ],
  },
  mouse: {
    padding: 2.5,
    styles: [
      "transform: translate(1px, 2px) rotate(0deg)",
      "transform: translate(-1px, 4px) rotate(-90deg)",
      "transform: translate(0px, 1px) rotate(0deg)",
      "transform: translate(-1px, 0px) rotate(90deg)",
      "transform: translate(3px, 4px) rotate(0deg)",
      "transform: translate(1px, 2px) rotate(180deg)",
      "transform: translate(5px, 2px) rotate(-45deg)",
    ],
  },
  rabbit: {
    padding: 2,
    styles: [
      "transform: translate(2.5px, 2.328px) rotate(135deg)",
      "transform: translate(2.5px, -0.5px) rotate(45deg)",
      "transform: translate(3.5px, 2.328px) rotate(180deg)",
      "transform: translate(3.086px, 5.156px) rotate(-135deg)",
      "transform: translate(-0.328px, 5.156px) rotate(0deg)",
      "transform: translate(2.5px, -0.5px) rotate(45deg)",
      "transform: translate(-0.328px, -1.914px) rotate(45deg)",
    ],
  },
  rocket: {
    padding: 1.5,
    styles: [
      "transform: translate(-1px, 1px) rotate(0deg)",
      "transform: translate(-1px, 1px) rotate(-90deg)",
      "transform: translate(4.5px, 1.5px) rotate(90deg)",
      "transform: translate(4.5px, 1.5px) rotate(180deg) ",
      "transform: translate(1px, -1px) rotate(-180deg)",
      "transform: translate(1.5px, 2.5px) rotate(0deg)",
      "transform: translate(2.5px, 5.5px) rotate(-90deg)",
    ],
  },
  scorpion: {
    padding: 2,
    styles: [
      "transform: translate(3px, 2.414px) rotate(180deg)",
      "transform: translate(0.5px, 2.414px) rotate(-45deg)",
      "transform: translate(1px, -1px) rotate(45deg)",
      "transform: translate(-1px, 3.828px) rotate(-45deg)",
      "transform: translate(3.328px, 1px) rotate(90deg)",
      "transform: translate(3px, -1px) rotate(0deg)",
      "transform: translate(1px, -1px) rotate(0deg)",
    ],
  },
  serpent: {
    padding: 3.5,
    styles: [
      "transform: translate(2px, 2.5px) rotate(180deg)",
      "transform: translate(4px, 2.5px) rotate(90deg)",
      "transform: translate(6.414px, 1.5px) rotate(-90deg)",
      "transform: translate(6.828px, 1.914px) rotate(-135deg)",
      "transform: translate(2px, 2.5px) rotate(0deg)",
      "transform: translate(4px, 0.5px) rotate(45deg)",
      "transform: translate(-3px, 3.5px) rotate(0deg)",
    ],
  },
  swan: {
    padding: 1.5,
    styles: [
      "transform: translate(1.414px, 2.086px) rotate(45deg)",
      "transform: translate(5.414px, 2.086px) rotate(90deg)",
      "transform: translate(1px, -0.086px) rotate(-135deg)",
      "transform: translate(0px, 1.5px) rotate(90deg)",
      "transform: translate(1.414px, 2.086px) rotate(135deg)",
      "transform: translate(0px, 1.5px) rotate(0deg)",
      "transform: translate(1px, -1.5px) rotate(90deg)",
    ],
  },
};
